version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: kafka-large-payload-processor-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: testdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Seoul
